# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CWord\课程学习\网络安全协议分析\DNS_sniff\gui\ui\dnsDetectionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dnsDetectionWindow(object):
    def setupUi(self, dnsDetectionWindow):
        dnsDetectionWindow.setObjectName("dnsDetectionWindow")
        dnsDetectionWindow.setEnabled(True)
        dnsDetectionWindow.resize(1069, 771)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dnsDetectionWindow.sizePolicy().hasHeightForWidth())
        dnsDetectionWindow.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(dnsDetectionWindow)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_detect = PrimaryPushButton(dnsDetectionWindow)
        self.pushButton_detect.setObjectName("pushButton_detect")
        self.horizontalLayout.addWidget(self.pushButton_detect)
        self.pushButton_attack_simulation = PushButton(dnsDetectionWindow)
        self.pushButton_attack_simulation.setObjectName("pushButton_attack_simulation")
        self.horizontalLayout.addWidget(self.pushButton_attack_simulation)
        self.checkBox_only_detect_DNS = CheckBox(dnsDetectionWindow)
        self.checkBox_only_detect_DNS.setEnabled(False)
        self.checkBox_only_detect_DNS.setCheckable(True)
        self.checkBox_only_detect_DNS.setChecked(True)
        self.checkBox_only_detect_DNS.setTristate(False)
        self.checkBox_only_detect_DNS.setObjectName("checkBox_only_detect_DNS")
        self.horizontalLayout.addWidget(self.checkBox_only_detect_DNS)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 2, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.tableWidget_traffic_detection_list = TableWidget(dnsDetectionWindow)
        self.tableWidget_traffic_detection_list.setMinimumSize(QtCore.QSize(900, 0))
        self.tableWidget_traffic_detection_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_traffic_detection_list.setObjectName("tableWidget_traffic_detection_list")
        self.tableWidget_traffic_detection_list.setColumnCount(0)
        self.tableWidget_traffic_detection_list.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_traffic_detection_list)
        self.widget_detection_chart = QtWidgets.QWidget(dnsDetectionWindow)
        self.widget_detection_chart.setMinimumSize(QtCore.QSize(0, 300))
        self.widget_detection_chart.setObjectName("widget_detection_chart")
        self.verticalLayout.addWidget(self.widget_detection_chart)
        spacerItem2 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(dnsDetectionWindow)
        QtCore.QMetaObject.connectSlotsByName(dnsDetectionWindow)

    def retranslateUi(self, dnsDetectionWindow):
        _translate = QtCore.QCoreApplication.translate
        dnsDetectionWindow.setWindowTitle(_translate("dnsDetectionWindow", "DNS sniff V1.0 by GZHU"))
        self.pushButton_detect.setText(_translate("dnsDetectionWindow", "开始检测"))
        self.pushButton_attack_simulation.setText(_translate("dnsDetectionWindow", "攻击模拟"))
        self.checkBox_only_detect_DNS.setText(_translate("dnsDetectionWindow", "DNS协议"))
from qfluentwidgets import CheckBox, PrimaryPushButton, PushButton
from qfluentwidgets  import TableWidget
